/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CAST_VOTE_DISCRIMINATOR = 18;

export function getCastVoteDiscriminatorBytes() {
  return getU8Encoder().encode(CAST_VOTE_DISCRIMINATOR);
}

export type CastVoteInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountEpochState extends string | IAccountMeta<string> = string,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountEpochSnapshot extends string | IAccountMeta<string> = string,
  TAccountConsensusResult extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountEpochState extends string
        ? WritableAccount<TAccountEpochState>
        : TAccountEpochState,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountEpochSnapshot extends string
        ? ReadonlyAccount<TAccountEpochSnapshot>
        : TAccountEpochSnapshot,
      TAccountConsensusResult extends string
        ? WritableAccount<TAccountConsensusResult>
        : TAccountConsensusResult,
      ...TRemainingAccounts,
    ]
  >;

export type CastVoteInstructionData = {
  discriminator: number;
  epoch: bigint;
  aggSig: ReadonlyUint8Array;
  apk2: ReadonlyUint8Array;
  signersBitmap: ReadonlyUint8Array;
  message: ReadonlyUint8Array;
};

export type CastVoteInstructionDataArgs = {
  epoch: number | bigint;
  aggSig: ReadonlyUint8Array;
  apk2: ReadonlyUint8Array;
  signersBitmap: ReadonlyUint8Array;
  message: ReadonlyUint8Array;
};

export function getCastVoteInstructionDataEncoder(): Encoder<CastVoteInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['epoch', getU64Encoder()],
      ['aggSig', fixEncoderSize(getBytesEncoder(), 32)],
      ['apk2', fixEncoderSize(getBytesEncoder(), 64)],
      [
        'signersBitmap',
        addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
      ],
      ['message', fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: CAST_VOTE_DISCRIMINATOR })
  );
}

export function getCastVoteInstructionDataDecoder(): Decoder<CastVoteInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['epoch', getU64Decoder()],
    ['aggSig', fixDecoderSize(getBytesDecoder(), 32)],
    ['apk2', fixDecoderSize(getBytesDecoder(), 64)],
    ['signersBitmap', addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
    ['message', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getCastVoteInstructionDataCodec(): Codec<
  CastVoteInstructionDataArgs,
  CastVoteInstructionData
> {
  return combineCodec(
    getCastVoteInstructionDataEncoder(),
    getCastVoteInstructionDataDecoder()
  );
}

export type CastVoteInput<
  TAccountEpochState extends string = string,
  TAccountConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountEpochSnapshot extends string = string,
  TAccountConsensusResult extends string = string,
> = {
  epochState: Address<TAccountEpochState>;
  config: Address<TAccountConfig>;
  ncn: Address<TAccountNcn>;
  epochSnapshot: Address<TAccountEpochSnapshot>;
  consensusResult: Address<TAccountConsensusResult>;
  epoch: CastVoteInstructionDataArgs['epoch'];
  aggSig: CastVoteInstructionDataArgs['aggSig'];
  apk2: CastVoteInstructionDataArgs['apk2'];
  signersBitmap: CastVoteInstructionDataArgs['signersBitmap'];
  message: CastVoteInstructionDataArgs['message'];
};

export function getCastVoteInstruction<
  TAccountEpochState extends string,
  TAccountConfig extends string,
  TAccountNcn extends string,
  TAccountEpochSnapshot extends string,
  TAccountConsensusResult extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: CastVoteInput<
    TAccountEpochState,
    TAccountConfig,
    TAccountNcn,
    TAccountEpochSnapshot,
    TAccountConsensusResult
  >,
  config?: { programAddress?: TProgramAddress }
): CastVoteInstruction<
  TProgramAddress,
  TAccountEpochState,
  TAccountConfig,
  TAccountNcn,
  TAccountEpochSnapshot,
  TAccountConsensusResult
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    epochState: { value: input.epochState ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    ncn: { value: input.ncn ?? null, isWritable: false },
    epochSnapshot: { value: input.epochSnapshot ?? null, isWritable: false },
    consensusResult: { value: input.consensusResult ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.epochState),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.epochSnapshot),
      getAccountMeta(accounts.consensusResult),
    ],
    programAddress,
    data: getCastVoteInstructionDataEncoder().encode(
      args as CastVoteInstructionDataArgs
    ),
  } as CastVoteInstruction<
    TProgramAddress,
    TAccountEpochState,
    TAccountConfig,
    TAccountNcn,
    TAccountEpochSnapshot,
    TAccountConsensusResult
  >;

  return instruction;
}

export type ParsedCastVoteInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    epochState: TAccountMetas[0];
    config: TAccountMetas[1];
    ncn: TAccountMetas[2];
    epochSnapshot: TAccountMetas[3];
    consensusResult: TAccountMetas[4];
  };
  data: CastVoteInstructionData;
};

export function parseCastVoteInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCastVoteInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      epochState: getNextAccount(),
      config: getNextAccount(),
      ncn: getNextAccount(),
      epochSnapshot: getNextAccount(),
      consensusResult: getNextAccount(),
    },
    data: getCastVoteInstructionDataDecoder().decode(instruction.data),
  };
}
