/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INITIALIZE_EPOCH_SNAPSHOT_DISCRIMINATOR = 10;

export function getInitializeEpochSnapshotDiscriminatorBytes() {
  return getU8Encoder().encode(INITIALIZE_EPOCH_SNAPSHOT_DISCRIMINATOR);
}

export type InitializeEpochSnapshotInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountEpochMarker extends string | IAccountMeta<string> = string,
  TAccountEpochState extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountEpochSnapshot extends string | IAccountMeta<string> = string,
  TAccountAccountPayer extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountEpochMarker extends string
        ? ReadonlyAccount<TAccountEpochMarker>
        : TAccountEpochMarker,
      TAccountEpochState extends string
        ? WritableAccount<TAccountEpochState>
        : TAccountEpochState,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountEpochSnapshot extends string
        ? WritableAccount<TAccountEpochSnapshot>
        : TAccountEpochSnapshot,
      TAccountAccountPayer extends string
        ? WritableAccount<TAccountAccountPayer>
        : TAccountAccountPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeEpochSnapshotInstructionData = {
  discriminator: number;
  epoch: bigint;
};

export type InitializeEpochSnapshotInstructionDataArgs = {
  epoch: number | bigint;
};

export function getInitializeEpochSnapshotInstructionDataEncoder(): Encoder<InitializeEpochSnapshotInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_EPOCH_SNAPSHOT_DISCRIMINATOR,
    })
  );
}

export function getInitializeEpochSnapshotInstructionDataDecoder(): Decoder<InitializeEpochSnapshotInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getInitializeEpochSnapshotInstructionDataCodec(): Codec<
  InitializeEpochSnapshotInstructionDataArgs,
  InitializeEpochSnapshotInstructionData
> {
  return combineCodec(
    getInitializeEpochSnapshotInstructionDataEncoder(),
    getInitializeEpochSnapshotInstructionDataDecoder()
  );
}

export type InitializeEpochSnapshotInput<
  TAccountEpochMarker extends string = string,
  TAccountEpochState extends string = string,
  TAccountNcn extends string = string,
  TAccountEpochSnapshot extends string = string,
  TAccountAccountPayer extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  epochMarker: Address<TAccountEpochMarker>;
  epochState: Address<TAccountEpochState>;
  ncn: Address<TAccountNcn>;
  epochSnapshot: Address<TAccountEpochSnapshot>;
  accountPayer: Address<TAccountAccountPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
  epoch: InitializeEpochSnapshotInstructionDataArgs['epoch'];
};

export function getInitializeEpochSnapshotInstruction<
  TAccountEpochMarker extends string,
  TAccountEpochState extends string,
  TAccountNcn extends string,
  TAccountEpochSnapshot extends string,
  TAccountAccountPayer extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: InitializeEpochSnapshotInput<
    TAccountEpochMarker,
    TAccountEpochState,
    TAccountNcn,
    TAccountEpochSnapshot,
    TAccountAccountPayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeEpochSnapshotInstruction<
  TProgramAddress,
  TAccountEpochMarker,
  TAccountEpochState,
  TAccountNcn,
  TAccountEpochSnapshot,
  TAccountAccountPayer,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    epochMarker: { value: input.epochMarker ?? null, isWritable: false },
    epochState: { value: input.epochState ?? null, isWritable: true },
    ncn: { value: input.ncn ?? null, isWritable: false },
    epochSnapshot: { value: input.epochSnapshot ?? null, isWritable: true },
    accountPayer: { value: input.accountPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.epochMarker),
      getAccountMeta(accounts.epochState),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.epochSnapshot),
      getAccountMeta(accounts.accountPayer),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeEpochSnapshotInstructionDataEncoder().encode(
      args as InitializeEpochSnapshotInstructionDataArgs
    ),
  } as InitializeEpochSnapshotInstruction<
    TProgramAddress,
    TAccountEpochMarker,
    TAccountEpochState,
    TAccountNcn,
    TAccountEpochSnapshot,
    TAccountAccountPayer,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedInitializeEpochSnapshotInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    epochMarker: TAccountMetas[0];
    epochState: TAccountMetas[1];
    ncn: TAccountMetas[2];
    epochSnapshot: TAccountMetas[3];
    accountPayer: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: InitializeEpochSnapshotInstructionData;
};

export function parseInitializeEpochSnapshotInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedInitializeEpochSnapshotInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      epochMarker: getNextAccount(),
      epochState: getNextAccount(),
      ncn: getNextAccount(),
      epochSnapshot: getNextAccount(),
      accountPayer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeEpochSnapshotInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
