/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INITIALIZE_OPERATOR_REGISTRY_DISCRIMINATOR = 3;

export function getInitializeOperatorRegistryDiscriminatorBytes() {
  return getU8Encoder().encode(INITIALIZE_OPERATOR_REGISTRY_DISCRIMINATOR);
}

export type InitializeOperatorRegistryInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountOperatorRegistry extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountAccountPayer extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountOperatorRegistry extends string
        ? WritableAccount<TAccountOperatorRegistry>
        : TAccountOperatorRegistry,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountAccountPayer extends string
        ? WritableAccount<TAccountAccountPayer>
        : TAccountAccountPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeOperatorRegistryInstructionData = {
  discriminator: number;
};

export type InitializeOperatorRegistryInstructionDataArgs = {};

export function getInitializeOperatorRegistryInstructionDataEncoder(): Encoder<InitializeOperatorRegistryInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_OPERATOR_REGISTRY_DISCRIMINATOR,
    })
  );
}

export function getInitializeOperatorRegistryInstructionDataDecoder(): Decoder<InitializeOperatorRegistryInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getInitializeOperatorRegistryInstructionDataCodec(): Codec<
  InitializeOperatorRegistryInstructionDataArgs,
  InitializeOperatorRegistryInstructionData
> {
  return combineCodec(
    getInitializeOperatorRegistryInstructionDataEncoder(),
    getInitializeOperatorRegistryInstructionDataDecoder()
  );
}

export type InitializeOperatorRegistryInput<
  TAccountConfig extends string = string,
  TAccountOperatorRegistry extends string = string,
  TAccountNcn extends string = string,
  TAccountAccountPayer extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  config: Address<TAccountConfig>;
  operatorRegistry: Address<TAccountOperatorRegistry>;
  ncn: Address<TAccountNcn>;
  accountPayer: Address<TAccountAccountPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getInitializeOperatorRegistryInstruction<
  TAccountConfig extends string,
  TAccountOperatorRegistry extends string,
  TAccountNcn extends string,
  TAccountAccountPayer extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: InitializeOperatorRegistryInput<
    TAccountConfig,
    TAccountOperatorRegistry,
    TAccountNcn,
    TAccountAccountPayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeOperatorRegistryInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountOperatorRegistry,
  TAccountNcn,
  TAccountAccountPayer,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    operatorRegistry: {
      value: input.operatorRegistry ?? null,
      isWritable: true,
    },
    ncn: { value: input.ncn ?? null, isWritable: false },
    accountPayer: { value: input.accountPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.operatorRegistry),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.accountPayer),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeOperatorRegistryInstructionDataEncoder().encode({}),
  } as InitializeOperatorRegistryInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountOperatorRegistry,
    TAccountNcn,
    TAccountAccountPayer,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedInitializeOperatorRegistryInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    operatorRegistry: TAccountMetas[1];
    ncn: TAccountMetas[2];
    accountPayer: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: InitializeOperatorRegistryInstructionData;
};

export function parseInitializeOperatorRegistryInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedInitializeOperatorRegistryInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      operatorRegistry: getNextAccount(),
      ncn: getNextAccount(),
      accountPayer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeOperatorRegistryInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
