/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const REALLOC_EPOCH_SNAPSHOT_DISCRIMINATOR = 8;

export function getReallocEpochSnapshotDiscriminatorBytes() {
  return getU8Encoder().encode(REALLOC_EPOCH_SNAPSHOT_DISCRIMINATOR);
}

export type ReallocEpochSnapshotInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountEpochSnapshot extends string | IAccountMeta<string> = string,
  TAccountAccountPayer extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountEpochSnapshot extends string
        ? WritableAccount<TAccountEpochSnapshot>
        : TAccountEpochSnapshot,
      TAccountAccountPayer extends string
        ? WritableAccount<TAccountAccountPayer>
        : TAccountAccountPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ReallocEpochSnapshotInstructionData = {
  discriminator: number;
  epoch: bigint;
};

export type ReallocEpochSnapshotInstructionDataArgs = {
  epoch: number | bigint;
};

export function getReallocEpochSnapshotInstructionDataEncoder(): Encoder<ReallocEpochSnapshotInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: REALLOC_EPOCH_SNAPSHOT_DISCRIMINATOR,
    })
  );
}

export function getReallocEpochSnapshotInstructionDataDecoder(): Decoder<ReallocEpochSnapshotInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getReallocEpochSnapshotInstructionDataCodec(): Codec<
  ReallocEpochSnapshotInstructionDataArgs,
  ReallocEpochSnapshotInstructionData
> {
  return combineCodec(
    getReallocEpochSnapshotInstructionDataEncoder(),
    getReallocEpochSnapshotInstructionDataDecoder()
  );
}

export type ReallocEpochSnapshotInput<
  TAccountNcn extends string = string,
  TAccountConfig extends string = string,
  TAccountEpochSnapshot extends string = string,
  TAccountAccountPayer extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  ncn: Address<TAccountNcn>;
  config: Address<TAccountConfig>;
  epochSnapshot: Address<TAccountEpochSnapshot>;
  accountPayer: Address<TAccountAccountPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
  epoch: ReallocEpochSnapshotInstructionDataArgs['epoch'];
};

export function getReallocEpochSnapshotInstruction<
  TAccountNcn extends string,
  TAccountConfig extends string,
  TAccountEpochSnapshot extends string,
  TAccountAccountPayer extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: ReallocEpochSnapshotInput<
    TAccountNcn,
    TAccountConfig,
    TAccountEpochSnapshot,
    TAccountAccountPayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): ReallocEpochSnapshotInstruction<
  TProgramAddress,
  TAccountNcn,
  TAccountConfig,
  TAccountEpochSnapshot,
  TAccountAccountPayer,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    ncn: { value: input.ncn ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    epochSnapshot: { value: input.epochSnapshot ?? null, isWritable: true },
    accountPayer: { value: input.accountPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.epochSnapshot),
      getAccountMeta(accounts.accountPayer),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getReallocEpochSnapshotInstructionDataEncoder().encode(
      args as ReallocEpochSnapshotInstructionDataArgs
    ),
  } as ReallocEpochSnapshotInstruction<
    TProgramAddress,
    TAccountNcn,
    TAccountConfig,
    TAccountEpochSnapshot,
    TAccountAccountPayer,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedReallocEpochSnapshotInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    ncn: TAccountMetas[0];
    config: TAccountMetas[1];
    epochSnapshot: TAccountMetas[2];
    accountPayer: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: ReallocEpochSnapshotInstructionData;
};

export function parseReallocEpochSnapshotInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedReallocEpochSnapshotInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      ncn: getNextAccount(),
      config: getNextAccount(),
      epochSnapshot: getNextAccount(),
      accountPayer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getReallocEpochSnapshotInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
