/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SNAPSHOT_VAULT_OPERATOR_DELEGATION_DISCRIMINATOR = 8;

export function getSnapshotVaultOperatorDelegationDiscriminatorBytes() {
  return getU8Encoder().encode(
    SNAPSHOT_VAULT_OPERATOR_DELEGATION_DISCRIMINATOR
  );
}

export type SnapshotVaultOperatorDelegationInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountRestakingConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountOperator extends string | IAccountMeta<string> = string,
  TAccountVault extends string | IAccountMeta<string> = string,
  TAccountVaultNcnTicket extends string | IAccountMeta<string> = string,
  TAccountNcnVaultTicket extends string | IAccountMeta<string> = string,
  TAccountNcnOperatorState extends string | IAccountMeta<string> = string,
  TAccountVaultOperatorDelegation extends
    | string
    | IAccountMeta<string> = string,
  TAccountSnapshot extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRestakingConfig extends string
        ? ReadonlyAccount<TAccountRestakingConfig>
        : TAccountRestakingConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountOperator extends string
        ? ReadonlyAccount<TAccountOperator>
        : TAccountOperator,
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountVaultNcnTicket extends string
        ? ReadonlyAccount<TAccountVaultNcnTicket>
        : TAccountVaultNcnTicket,
      TAccountNcnVaultTicket extends string
        ? ReadonlyAccount<TAccountNcnVaultTicket>
        : TAccountNcnVaultTicket,
      TAccountNcnOperatorState extends string
        ? ReadonlyAccount<TAccountNcnOperatorState>
        : TAccountNcnOperatorState,
      TAccountVaultOperatorDelegation extends string
        ? ReadonlyAccount<TAccountVaultOperatorDelegation>
        : TAccountVaultOperatorDelegation,
      TAccountSnapshot extends string
        ? WritableAccount<TAccountSnapshot>
        : TAccountSnapshot,
      ...TRemainingAccounts,
    ]
  >;

export type SnapshotVaultOperatorDelegationInstructionData = {
  discriminator: number;
};

export type SnapshotVaultOperatorDelegationInstructionDataArgs = {};

export function getSnapshotVaultOperatorDelegationInstructionDataEncoder(): Encoder<SnapshotVaultOperatorDelegationInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: SNAPSHOT_VAULT_OPERATOR_DELEGATION_DISCRIMINATOR,
    })
  );
}

export function getSnapshotVaultOperatorDelegationInstructionDataDecoder(): Decoder<SnapshotVaultOperatorDelegationInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getSnapshotVaultOperatorDelegationInstructionDataCodec(): Codec<
  SnapshotVaultOperatorDelegationInstructionDataArgs,
  SnapshotVaultOperatorDelegationInstructionData
> {
  return combineCodec(
    getSnapshotVaultOperatorDelegationInstructionDataEncoder(),
    getSnapshotVaultOperatorDelegationInstructionDataDecoder()
  );
}

export type SnapshotVaultOperatorDelegationInput<
  TAccountConfig extends string = string,
  TAccountRestakingConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountOperator extends string = string,
  TAccountVault extends string = string,
  TAccountVaultNcnTicket extends string = string,
  TAccountNcnVaultTicket extends string = string,
  TAccountNcnOperatorState extends string = string,
  TAccountVaultOperatorDelegation extends string = string,
  TAccountSnapshot extends string = string,
> = {
  config: Address<TAccountConfig>;
  restakingConfig: Address<TAccountRestakingConfig>;
  ncn: Address<TAccountNcn>;
  operator: Address<TAccountOperator>;
  vault: Address<TAccountVault>;
  vaultNcnTicket: Address<TAccountVaultNcnTicket>;
  ncnVaultTicket: Address<TAccountNcnVaultTicket>;
  ncnOperatorState: Address<TAccountNcnOperatorState>;
  vaultOperatorDelegation: Address<TAccountVaultOperatorDelegation>;
  snapshot: Address<TAccountSnapshot>;
};

export function getSnapshotVaultOperatorDelegationInstruction<
  TAccountConfig extends string,
  TAccountRestakingConfig extends string,
  TAccountNcn extends string,
  TAccountOperator extends string,
  TAccountVault extends string,
  TAccountVaultNcnTicket extends string,
  TAccountNcnVaultTicket extends string,
  TAccountNcnOperatorState extends string,
  TAccountVaultOperatorDelegation extends string,
  TAccountSnapshot extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: SnapshotVaultOperatorDelegationInput<
    TAccountConfig,
    TAccountRestakingConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountVault,
    TAccountVaultNcnTicket,
    TAccountNcnVaultTicket,
    TAccountNcnOperatorState,
    TAccountVaultOperatorDelegation,
    TAccountSnapshot
  >,
  config?: { programAddress?: TProgramAddress }
): SnapshotVaultOperatorDelegationInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountRestakingConfig,
  TAccountNcn,
  TAccountOperator,
  TAccountVault,
  TAccountVaultNcnTicket,
  TAccountNcnVaultTicket,
  TAccountNcnOperatorState,
  TAccountVaultOperatorDelegation,
  TAccountSnapshot
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    restakingConfig: {
      value: input.restakingConfig ?? null,
      isWritable: false,
    },
    ncn: { value: input.ncn ?? null, isWritable: false },
    operator: { value: input.operator ?? null, isWritable: false },
    vault: { value: input.vault ?? null, isWritable: false },
    vaultNcnTicket: { value: input.vaultNcnTicket ?? null, isWritable: false },
    ncnVaultTicket: { value: input.ncnVaultTicket ?? null, isWritable: false },
    ncnOperatorState: {
      value: input.ncnOperatorState ?? null,
      isWritable: false,
    },
    vaultOperatorDelegation: {
      value: input.vaultOperatorDelegation ?? null,
      isWritable: false,
    },
    snapshot: { value: input.snapshot ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.restakingConfig),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.vaultNcnTicket),
      getAccountMeta(accounts.ncnVaultTicket),
      getAccountMeta(accounts.ncnOperatorState),
      getAccountMeta(accounts.vaultOperatorDelegation),
      getAccountMeta(accounts.snapshot),
    ],
    programAddress,
    data: getSnapshotVaultOperatorDelegationInstructionDataEncoder().encode({}),
  } as SnapshotVaultOperatorDelegationInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountRestakingConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountVault,
    TAccountVaultNcnTicket,
    TAccountNcnVaultTicket,
    TAccountNcnOperatorState,
    TAccountVaultOperatorDelegation,
    TAccountSnapshot
  >;

  return instruction;
}

export type ParsedSnapshotVaultOperatorDelegationInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    restakingConfig: TAccountMetas[1];
    ncn: TAccountMetas[2];
    operator: TAccountMetas[3];
    vault: TAccountMetas[4];
    vaultNcnTicket: TAccountMetas[5];
    ncnVaultTicket: TAccountMetas[6];
    ncnOperatorState: TAccountMetas[7];
    vaultOperatorDelegation: TAccountMetas[8];
    snapshot: TAccountMetas[9];
  };
  data: SnapshotVaultOperatorDelegationInstructionData;
};

export function parseSnapshotVaultOperatorDelegationInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSnapshotVaultOperatorDelegationInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      restakingConfig: getNextAccount(),
      ncn: getNextAccount(),
      operator: getNextAccount(),
      vault: getNextAccount(),
      vaultNcnTicket: getNextAccount(),
      ncnVaultTicket: getNextAccount(),
      ncnOperatorState: getNextAccount(),
      vaultOperatorDelegation: getNextAccount(),
      snapshot: getNextAccount(),
    },
    data: getSnapshotVaultOperatorDelegationInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
