# placeholders for clippy and other tools
# Program IDs may not be correct
[env]
NCN_PROGRAM_ID = "3fKQSi6VzzDUJSmeksS8qK6RB3Gs3UoZWtsQD3xagy45"
RESTAKING_PROGRAM_ID = "RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q"
VAULT_PROGRAM_ID = "Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"
