/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type EpochAccountStatus = { epochState: number; weightTable: number };

export type EpochAccountStatusArgs = EpochAccountStatus;

export function getEpochAccountStatusEncoder(): Encoder<EpochAccountStatusArgs> {
  return getStructEncoder([
    ['epochState', getU8Encoder()],
    ['weightTable', getU8Encoder()],
  ]);
}

export function getEpochAccountStatusDecoder(): Decoder<EpochAccountStatus> {
  return getStructDecoder([
    ['epochState', getU8Decoder()],
    ['weightTable', getU8Decoder()],
  ]);
}

export function getEpochAccountStatusCodec(): Codec<
  EpochAccountStatusArgs,
  EpochAccountStatus
> {
  return combineCodec(
    getEpochAccountStatusEncoder(),
    getEpochAccountStatusDecoder()
  );
}
