/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBoolDecoder,
  getBoolEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  getStakeWeightsDecoder,
  getStakeWeightsEncoder,
  type StakeWeights,
  type StakeWeightsArgs,
} from '.';

export type OperatorSnapshot = {
  operator: Address;
  g1Pubkey: ReadonlyUint8Array;
  slotCreated: bigint;
  slotFinalized: bigint;
  isActive: number;
  ncnOperatorIndex: bigint;
  operatorIndex: bigint;
  hasMinimumStakeWeight: number;
  stakeWeightSoFar: StakeWeights;
  vaultOperatorDelegationCount: bigint;
  vaultOperatorDelegationsRegistered: bigint;
  validOperatorVaultDelegations: bigint;
  vaultsDelegated: Array<Address>;
};

export type OperatorSnapshotArgs = {
  operator: Address;
  g1Pubkey: ReadonlyUint8Array;
  slotCreated: number | bigint;
  slotFinalized: number | bigint;
  isActive: number;
  ncnOperatorIndex: number | bigint;
  operatorIndex: number | bigint;
  hasMinimumStakeWeight: number;
  stakeWeightSoFar: StakeWeightsArgs;
  vaultOperatorDelegationCount: number | bigint;
  vaultOperatorDelegationsRegistered: number | bigint;
  validOperatorVaultDelegations: number | bigint;
  vaultsDelegated: Array<Address>;
};

export function getOperatorSnapshotEncoder(): Encoder<OperatorSnapshotArgs> {
  return getStructEncoder([
    ['operator', getAddressEncoder()],
    ['g1Pubkey', fixEncoderSize(getBytesEncoder(), 32)],
    ['slotCreated', getU64Encoder()],
    ['slotFinalized', getU64Encoder()],
    ['isActive', getBoolEncoder()],
    ['ncnOperatorIndex', getU64Encoder()],
    ['operatorIndex', getU64Encoder()],
    ['hasMinimumStakeWeight', getBoolEncoder()],
    ['stakeWeightSoFar', getStakeWeightsEncoder()],
    ['vaultOperatorDelegationCount', getU64Encoder()],
    ['vaultOperatorDelegationsRegistered', getU64Encoder()],
    ['validOperatorVaultDelegations', getU64Encoder()],
    ['vaultsDelegated', getArrayEncoder(getAddressEncoder(), { size: 10 })],
  ]);
}

export function getOperatorSnapshotDecoder(): Decoder<OperatorSnapshot> {
  return getStructDecoder([
    ['operator', getAddressDecoder()],
    ['g1Pubkey', fixDecoderSize(getBytesDecoder(), 32)],
    ['slotCreated', getU64Decoder()],
    ['slotFinalized', getU64Decoder()],
    ['isActive', getBoolDecoder()],
    ['ncnOperatorIndex', getU64Decoder()],
    ['operatorIndex', getU64Decoder()],
    ['hasMinimumStakeWeight', getBoolDecoder()],
    ['stakeWeightSoFar', getStakeWeightsDecoder()],
    ['vaultOperatorDelegationCount', getU64Decoder()],
    ['vaultOperatorDelegationsRegistered', getU64Decoder()],
    ['validOperatorVaultDelegations', getU64Decoder()],
    ['vaultsDelegated', getArrayDecoder(getAddressDecoder(), { size: 10 })],
  ]);
}

export function getOperatorSnapshotCodec(): Codec<
  OperatorSnapshotArgs,
  OperatorSnapshot
> {
  return combineCodec(
    getOperatorSnapshotEncoder(),
    getOperatorSnapshotDecoder()
  );
}
