/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type OperatorEntry = {
  operatorPubkey: Address;
  g1Pubkey: ReadonlyUint8Array;
  g2Pubkey: ReadonlyUint8Array;
  operatorIndex: bigint;
  slotRegistered: bigint;
};

export type OperatorEntryArgs = {
  operatorPubkey: Address;
  g1Pubkey: ReadonlyUint8Array;
  g2Pubkey: ReadonlyUint8Array;
  operatorIndex: number | bigint;
  slotRegistered: number | bigint;
};

export function getOperatorEntryEncoder(): Encoder<OperatorEntryArgs> {
  return getStructEncoder([
    ['operatorPubkey', getAddressEncoder()],
    ['g1Pubkey', fixEncoderSize(getBytesEncoder(), 32)],
    ['g2Pubkey', fixEncoderSize(getBytesEncoder(), 64)],
    ['operatorIndex', getU64Encoder()],
    ['slotRegistered', getU64Encoder()],
  ]);
}

export function getOperatorEntryDecoder(): Decoder<OperatorEntry> {
  return getStructDecoder([
    ['operatorPubkey', getAddressDecoder()],
    ['g1Pubkey', fixDecoderSize(getBytesDecoder(), 32)],
    ['g2Pubkey', fixDecoderSize(getBytesDecoder(), 64)],
    ['operatorIndex', getU64Decoder()],
    ['slotRegistered', getU64Decoder()],
  ]);
}

export function getOperatorEntryCodec(): Codec<
  OperatorEntryArgs,
  OperatorEntry
> {
  return combineCodec(getOperatorEntryEncoder(), getOperatorEntryDecoder());
}
