/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type StMintEntry = {
  stMint: Address;
  reserveSwitchboardFeed: ReadonlyUint8Array;
};

export type StMintEntryArgs = StMintEntry;

export function getStMintEntryEncoder(): Encoder<StMintEntryArgs> {
  return getStructEncoder([
    ['stMint', getAddressEncoder()],
    ['reserveSwitchboardFeed', fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

export function getStMintEntryDecoder(): Decoder<StMintEntry> {
  return getStructDecoder([
    ['stMint', getAddressDecoder()],
    ['reserveSwitchboardFeed', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getStMintEntryCodec(): Codec<StMintEntryArgs, StMintEntry> {
  return combineCodec(getStMintEntryEncoder(), getStMintEntryDecoder());
}
